spring: 

  profiles:

    active:

    - dev

--- 

server:

  port: 8001

spring: 

   profiles: dev

   application: 

    name: microservicecloud-config-dept-client

   datasource:

    type: com.alibaba.druid.pool.DruidDataSource

    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost/cloudDB03?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false

    username: root

    password: 123456

    dbcp2:

      min-idle: 5

      initial-size: 5

      max-total: 5

      max-wait-millis: 200 

mybatis:

  config-location: classpath:mybatis/mybatis.cfg.xml

  type-aliases-package: com.atguigu.springcloud.entities

  mapper-locations:

  - classpath:mybatis/mapper/**/*.xml



eureka: 

  client: #客户端注册进eureka服务列表内

    register-with-eureka: false     #false表示不向注册中心注册自己。

    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务

    service-url: 

      defaultZone: http://eureka7001.com:7001/eureka

  instance:

    instance-id: dept-8001.com

    prefer-ip-address: true



info:

  app.name: atguigu-microservicecloud-springcloudconfig01

  company.name: www.atguigu.com

  build.artifactId: $project.artifactId$

  build.version: $project.version$

---

server:

  port: 8001

spring: 

   profiles: test

   application: 

    name: microservicecloud-config-dept-client

   datasource:

    type: com.alibaba.druid.pool.DruidDataSource

    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost/cloudDB03?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false

    username: root

    password: 123456

    dbcp2:

      min-idle: 5

      initial-size: 5

      max-total: 5

      max-wait-millis: 200  

  

  

mybatis:

  config-location: classpath:mybatis/mybatis.cfg.xml

  type-aliases-package: com.atguigu.springcloud.entities

  mapper-locations:

  - classpath:mybatis/mapper/**/*.xml



eureka: 

  client: #客户端注册进eureka服务列表内

    register-with-eureka: false     #false表示不向注册中心注册自己。

    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务

    service-url: 

      defaultZone: http://eureka7001.com:7001/eureka

  instance:

    instance-id: dept-8001.com

    prefer-ip-address: true



info:

  app.name: atguigu-microservicecloud-springcloudconfig02

  company.name: www.atguigu.com

  build.artifactId: $project.artifactId$

  build.version: $project.version$